<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="NewFolder1\**" />
    <Compile Remove="NewFolder2\**" />
    <EmbeddedResource Remove="NewFolder1\**" />
    <EmbeddedResource Remove="NewFolder2\**" />
    <None Remove="NewFolder1\**" />
    <None Remove="NewFolder2\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.3" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="SendGrid.Extensions.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="X.PagedList" Version="10.5.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Codeji.CMS.Repository\Codeji.CMS.Repository.csproj" />
    <ProjectReference Include="..\Codeji.CMS.DTO\Codeji.CMS.DTO.csproj" />
    <ProjectReference Include="..\Codeji.CMS.Utility\Codeji.CMS.Utility.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Recruitments\" />
    <None Remove="Recruitments\Interface\" />
  </ItemGroup>
</Project>