<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <ItemGroup>
    <Compile Remove="Upload\**" />
    <Content Remove="Upload\**" />
    <EmbeddedResource Remove="Upload\**" />
    <None Remove="Upload\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Codeji.CMS.Repository\Codeji.CMS.Repository.csproj" />
    <ProjectReference Include="..\Codeji.CMS.Services\Codeji.CMS.Services.csproj" />
    <ProjectReference Include="..\Codeji.CMS.DTO\Codeji.CMS.DTO.csproj" />
    <ProjectReference Include="..\Codeji.CMS.Utility\Codeji.CMS.Utility.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Upload\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
    <Folder Include="Uploads\ProfileImage\" />
    <Folder Include="Uploads\Resume\" />
  </ItemGroup>
</Project>